server {
    listen 80;
    listen [::]:80;
    server_name harpcast.wetterheidi.de;

    root /apps/harpcast;
    index index.html;

    auth_basic "wetterheidi tools";
    auth_basic_user_file /etc/nginx/.htpasswd-wetterheidi;

    location / {
        try_files $uri $uri/ =404;
    }
}
